<?php

namespace Database\Seeders;

use App\Models\Team;
use App\Models\Customer;
use App\Models\User;
use Illuminate\Database\Seeder;

class CustomersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $company = Team::where('name', 'Copperbelt Mining Supplies Ltd')->first();

        if (!$company) {
            $this->command->error('Company not found. Run DemoCompanySeeder first.');
            return;
        }

        $admin = User::where('email', 'admin@copperbeltmining.com')->first();

        $customers = $this->getMiningCustomers();

        foreach ($customers as $customer) {
            Customer::create([
                'team_id' => $company->id,
                'customer_type' => $customer['type'],
                'salutation' => $customer['salutation'],
                'first_name' => $customer['first_name'],
                'last_name' => $customer['last_name'],
                'company_name' => $customer['company_name'] ?? '',
                'company_display_name' => $customer['company_display_name'] ?? '',
                'email' => $customer['email'],
                'phone' => $customer['phone'],
                'tpin' => $customer['tpin'],
                'branch_id' => $customer['branch_id'] ?? '',
                'payment_terms' => $customer['payment_terms'],
                'billing_country' => $customer['billing_country'],
                'billing_province' => $customer['billing_province'],
                'billing_city' => $customer['billing_city'],
                'billing_street_1' => $customer['billing_street_1'],
                'billing_street_2' => $customer['billing_street_2'] ?? '',
                'billing_phone' => $customer['billing_phone'],
                'shipping_country' => $customer['shipping_country'],
                'shipping_province' => $customer['shipping_province'],
                'shipping_city' => $customer['shipping_city'],
                'shipping_street_1' => $customer['shipping_street_1'],
                'shipping_street_2' => $customer['shipping_street_2'] ?? '',
                'shipping_phone' => $customer['shipping_phone'],
                'remarks' => $customer['remarks'] ?? '',
                'useYn' => true,
                'regrNm' => $admin->name ?? 'System',
                'regr_id' => $admin->id ?? null,
                'modrNm' => $admin->name ?? 'System',
                'modr_id' => $admin->id ?? null,
            ]);
        }

        $this->command->info('Customers created: ' . count($customers) . ' mining sector customers');
    }

    /**
     * Get comprehensive list of mining sector customers
     */
    protected function getMiningCustomers(): array
    {
        return [
            // ==================== MAJOR MINING COMPANIES ====================
            [
                'type' => 'Business',
                'salutation' => 'Mr',
                'first_name' => 'Michael',
                'last_name' => 'Musonda',
                'company_name' => 'Kansanshi Mining Plc',
                'company_display_name' => 'Kansanshi Mining Plc',
                'email' => 'procurement@kansanshi.com.zm',
                'phone' => '+260 977 123 456',
                'tpin' => '1000000001',
                'branch_id' => '001',
                'payment_terms' => 'Net 30',
                'billing_country' => 'Zambia',
                'billing_province' => 'North-Western',
                'billing_city' => 'Solwezi',
                'billing_street_1' => 'Kansanshi Mine Site',
                'billing_phone' => '+260 977 123 456',
                'shipping_country' => 'Zambia',
                'shipping_province' => 'North-Western',
                'shipping_city' => 'Solwezi',
                'shipping_street_1' => 'Kansanshi Mine Site - Receiving',
                'shipping_phone' => '+260 977 123 457',
                'remarks' => 'Tier 1 customer - Major copper mining operation. Credit limit: USD 500,000',
            ],
            [
                'type' => 'Business',
                'salutation' => 'Mr',
                'first_name' => 'David',
                'last_name' => 'Chileya',
                'company_name' => 'Mopani Copper Mines Plc',
                'company_display_name' => 'Mopani Copper Mines',
                'email' => 'supplychain@mopani.com.zm',
                'phone' => '+260 212 234 567',
                'tpin' => '1000000002',
                'branch_id' => '002',
                'payment_terms' => 'Net 45',
                'billing_country' => 'Zambia',
                'billing_province' => 'Copperbelt',
                'billing_city' => 'Kitwe',
                'billing_street_1' => 'Mindolo Road',
                'billing_street_2' => 'Nkana West',
                'billing_phone' => '+260 212 234 568',
                'shipping_country' => 'Zambia',
                'shipping_province' => 'Copperbelt',
                'shipping_city' => 'Kitwe',
                'shipping_street_1' => 'Mopani Nkana Concentrator',
                'shipping_street_2' => 'Receiving Bay 3',
                'shipping_phone' => '+260 212 234 569',
                'remarks' => 'Tier 1 customer - Underground copper mining. Credit limit: USD 400,000',
            ],
            [
                'type' => 'Business',
                'salutation' => 'Mrs',
                'first_name' => 'Esther',
                'last_name' => 'Mulenga',
                'company_name' => 'Konkola Copper Mines Plc',
                'company_display_name' => 'Konkola Copper Mines',
                'email' => 'procurement@kcm.co.zm',
                'phone' => '+260 212 345 678',
                'tpin' => '1000000003',
                'branch_id' => '003',
                'payment_terms' => 'Net 30',
                'billing_country' => 'Zambia',
                'billing_province' => 'Copperbelt',
                'billing_city' => 'Chingola',
                'billing_street_1' => 'Chililabombwe Road',
                'billing_phone' => '+260 212 345 679',
                'shipping_country' => 'Zambia',
                'shipping_province' => 'Copperbelt',
                'shipping_city' => 'Chingola',
                'shipping_street_1' => 'KCM Konkola Main Gate',
                'shipping_phone' => '+260 212 345 680',
                'remarks' => 'Tier 1 customer - Largest underground copper mine in Africa. Credit limit: USD 450,000',
            ],
            [
                'type' => 'Business',
                'salutation' => 'Mr',
                'first_name' => 'James',
                'last_name' => 'Sakala',
                'company_name' => 'Lubambe Copper Mine Ltd',
                'company_display_name' => 'Lubambe Copper Mine',
                'email' => 'purchasing@lubambe.com',
                'phone' => '+260 212 456 789',
                'tpin' => '1000000004',
                'branch_id' => '004',
                'payment_terms' => 'Net 30',
                'billing_country' => 'Zambia',
                'billing_province' => 'Copperbelt',
                'billing_city' => 'Chingola',
                'billing_street_1' => 'Chingola-Chililabombwe Road',
                'billing_phone' => '+260 212 456 790',
                'shipping_country' => 'Zambia',
                'shipping_province' => 'Copperbelt',
                'shipping_city' => 'Chingola',
                'shipping_street_1' => 'Lubambe Mine Access Road',
                'shipping_phone' => '+260 212 456 791',
                'remarks' => 'Joint venture copper mining operation. Credit limit: USD 200,000',
            ],
            [
                'type' => 'Business',
                'salutation' => 'Dr',
                'first_name' => 'Patrick',
                'last_name' => 'Mwamba',
                'company_name' => 'First Quantum Minerals Ltd',
                'company_display_name' => 'First Quantum Minerals',
                'email' => 'supply@fqm.com.zm',
                'phone' => '+260 977 567 890',
                'tpin' => '1000000005',
                'branch_id' => '005',
                'payment_terms' => 'Net 30',
                'billing_country' => 'Zambia',
                'billing_province' => 'North-Western',
                'billing_city' => 'Solwezi',
                'billing_street_1' => 'Sentinel Mine Site',
                'billing_phone' => '+260 977 567 891',
                'shipping_country' => 'Zambia',
                'shipping_province' => 'North-Western',
                'shipping_city' => 'Solwezi',
                'shipping_street_1' => 'Sentinel Mine Receiving',
                'shipping_phone' => '+260 977 567 892',
                'remarks' => 'Tier 1 customer - Parent company of Kansanshi. Credit limit: USD 600,000',
            ],

            // ==================== MINING CONTRACTORS ====================
            [
                'type' => 'Business',
                'salutation' => 'Mr',
                'first_name' => 'Robert',
                'last_name' => 'Phiri',
                'company_name' => 'Moolmans Mining Zambia Ltd',
                'company_display_name' => 'Moolmans Mining',
                'email' => 'procurement@moolmans.co.zm',
                'phone' => '+260 966 678 901',
                'tpin' => '1000000006',
                'branch_id' => '006',
                'payment_terms' => 'Net 30',
                'billing_country' => 'Zambia',
                'billing_province' => 'Copperbelt',
                'billing_city' => 'Kitwe',
                'billing_street_1' => 'Parklands Road',
                'billing_phone' => '+260 966 678 902',
                'shipping_country' => 'Zambia',
                'shipping_province' => 'Copperbelt',
                'shipping_city' => 'Kitwe',
                'shipping_street_1' => 'Moolmans Yard - Nkana',
                'shipping_phone' => '+260 966 678 903',
                'remarks' => 'Mining contractor - Open pit mining services. Credit limit: USD 150,000',
            ],
            [
                'type' => 'Business',
                'salutation' => 'Mr',
                'first_name' => 'Charles',
                'last_name' => 'Tembo',
                'company_name' => 'JCHX Mining Zambia Ltd',
                'company_display_name' => 'JCHX Mining',
                'email' => 'supply@jchx.co.zm',
                'phone' => '+260 955 789 012',
                'tpin' => '1000000007',
                'branch_id' => '007',
                'payment_terms' => 'Net 30',
                'billing_country' => 'Zambia',
                'billing_province' => 'Copperbelt',
                'billing_city' => 'Kitwe',
                'billing_street_1' => 'Industrial Area',
                'billing_phone' => '+260 955 789 013',
                'shipping_country' => 'Zambia',
                'shipping_province' => 'Copperbelt',
                'shipping_city' => 'Kitwe',
                'shipping_street_1' => 'JCHX Warehouse',
                'shipping_phone' => '+260 955 789 014',
                'remarks' => 'Chinese mining contractor - Underground development. Credit limit: USD 100,000',
            ],

            // ==================== DRILLING & EXPLORATION ====================
            [
                'type' => 'Business',
                'salutation' => 'Mr',
                'first_name' => 'Andrew',
                'last_name' => 'Zulu',
                'company_name' => 'Geotechnical Drilling Services Ltd',
                'company_display_name' => 'Geotechnical Drilling',
                'email' => 'info@geotechdrill.co.zm',
                'phone' => '+260 977 890 123',
                'tpin' => '1000000008',
                'branch_id' => '008',
                'payment_terms' => 'Net 15',
                'billing_country' => 'Zambia',
                'billing_province' => 'Copperbelt',
                'billing_city' => 'Ndola',
                'billing_street_1' => 'Bwafwano Road',
                'billing_phone' => '+260 977 890 124',
                'shipping_country' => 'Zambia',
                'shipping_province' => 'Copperbelt',
                'shipping_city' => 'Ndola',
                'shipping_street_1' => 'Geotech Drilling Yard',
                'shipping_phone' => '+260 977 890 125',
                'remarks' => 'Exploration drilling services. Credit limit: USD 50,000',
            ],
            [
                'type' => 'Business',
                'salutation' => 'Mr',
                'first_name' => 'Stanley',
                'last_name' => 'Chanda',
                'company_name' => 'Major Drilling Zambia Ltd',
                'company_display_name' => 'Major Drilling',
                'email' => 'zambia@majordrilling.com',
                'phone' => '+260 966 901 234',
                'tpin' => '1000000009',
                'branch_id' => '009',
                'payment_terms' => 'Net 30',
                'billing_country' => 'Zambia',
                'billing_province' => 'Copperbelt',
                'billing_city' => 'Kitwe',
                'billing_street_1' => 'Jambo Drive',
                'billing_phone' => '+260 966 901 235',
                'shipping_country' => 'Zambia',
                'shipping_province' => 'Copperbelt',
                'shipping_city' => 'Kitwe',
                'shipping_street_1' => 'Major Drilling Compound',
                'shipping_phone' => '+260 966 901 236',
                'remarks' => 'International drilling contractor. Credit limit: USD 75,000',
            ],

            // ==================== INDIVIDUAL CUSTOMERS ====================
            [
                'type' => 'Individual',
                'salutation' => 'Mr',
                'first_name' => 'Moses',
                'last_name' => 'Ng\'andu',
                'company_name' => '',
                'company_display_name' => 'Moses Ng\'andu',
                'email' => 'moses.ngandu@gmail.com',
                'phone' => '+260 977 012 345',
                'tpin' => '1000000010',
                'payment_terms' => 'Due on Receipt',
                'billing_country' => 'Zambia',
                'billing_province' => 'Copperbelt',
                'billing_city' => 'Kitwe',
                'billing_street_1' => 'Plot 456, Riverside',
                'billing_phone' => '+260 977 012 345',
                'shipping_country' => 'Zambia',
                'shipping_province' => 'Copperbelt',
                'shipping_city' => 'Kitwe',
                'shipping_street_1' => 'Plot 456, Riverside',
                'shipping_phone' => '+260 977 012 345',
                'remarks' => 'Small-scale mining consultant. Cash customer.',
            ],

            // ==================== SMELTERS & PROCESSORS ====================
            [
                'type' => 'Business',
                'salutation' => 'Mr',
                'first_name' => 'Emmanuel',
                'last_name' => 'Mutale',
                'company_name' => 'Chambishi Metals Plc',
                'company_display_name' => 'Chambishi Metals',
                'email' => 'procurement@chambishimetals.com',
                'phone' => '+260 212 123 456',
                'tpin' => '1000000011',
                'branch_id' => '011',
                'payment_terms' => 'Net 45',
                'billing_country' => 'Zambia',
                'billing_province' => 'Copperbelt',
                'billing_city' => 'Chambishi',
                'billing_street_1' => 'Chambishi Smelter Complex',
                'billing_phone' => '+260 212 123 457',
                'shipping_country' => 'Zambia',
                'shipping_province' => 'Copperbelt',
                'shipping_city' => 'Chambishi',
                'shipping_street_1' => 'Smelter Receiving Gate',
                'shipping_phone' => '+260 212 123 458',
                'remarks' => 'Copper/cobalt smelting and refining. Credit limit: USD 250,000',
            ],

            // ==================== LOGISTICS & TRANSPORT ====================
            [
                'type' => 'Business',
                'salutation' => 'Mr',
                'first_name' => 'Peter',
                'last_name' => 'Mwewa',
                'company_name' => 'Copperbelt Haulage Ltd',
                'company_display_name' => 'Copperbelt Haulage',
                'email' => 'logistics@copperbelthaulage.com',
                'phone' => '+260 955 234 567',
                'tpin' => '1000000012',
                'branch_id' => '012',
                'payment_terms' => 'Net 30',
                'billing_country' => 'Zambia',
                'billing_province' => 'Copperbelt',
                'billing_city' => 'Ndola',
                'billing_street_1' => 'Industrial Road',
                'billing_phone' => '+260 955 234 568',
                'shipping_country' => 'Zambia',
                'shipping_province' => 'Copperbelt',
                'shipping_city' => 'Ndola',
                'shipping_street_1' => 'CB Haulage Depot',
                'shipping_phone' => '+260 955 234 569',
                'remarks' => 'Mining logistics and transport. Credit limit: USD 80,000',
            ],
        ];
    }
}
