<?php

namespace Database\Seeders;

use App\Models\Team;
use App\Models\Item;
use App\Models\SalesAccount;
use App\Models\PurchasesAccount;
use App\Models\ItemGroup;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $company = Team::where('name', 'Copperbelt Mining Supplies Ltd')->first();

        if (!$company) {
            $this->command->error('Company not found. Run DemoCompanySeeder first.');
            return;
        }

        // Create sales and purchase accounts first
        $salesAccount = SalesAccount::firstOrCreate(
            ['name' => 'Sales Revenue'],
            ['team_id' => $company->id]
        );

        $purchaseAccount = PurchasesAccount::firstOrCreate(
            ['name' => 'Purchases'],
            ['team_id' => $company->id]
        );

        // Create item groups
        $itemGroups = $this->createItemGroups($company->id, $salesAccount->id, $purchaseAccount->id);

        // Create items
        $items = $this->getMiningSupplyItems($company->id, $salesAccount->id, $purchaseAccount->id);

        foreach ($items as $item) {
            Item::create($item);
        }

        $this->command->info('Items created: ' . count($items) . ' mining supply products');
    }

    protected function createItemGroups(int $teamId, int $salesAccountId, int $purchaseAccountId): array
    {
        $groups = [
            ['name' => 'Mining Equipment', 'type' => 'Inventory', 'description' => 'Heavy mining machinery and equipment'],
            ['name' => 'Drilling Equipment', 'type' => 'Inventory', 'description' => 'Drill rigs, drill bits, and drilling consumables'],
            ['name' => 'Safety Equipment', 'type' => 'Inventory', 'description' => 'PPE and safety gear'],
            ['name' => 'Spare Parts', 'type' => 'Inventory', 'description' => 'Machine spare parts and components'],
            ['name' => 'Consumables', 'type' => 'Inventory', 'description' => 'Mining consumables and supplies'],
            ['name' => 'Electrical Components', 'type' => 'Inventory', 'description' => 'Electrical parts and components'],
            ['name' => 'Pumps & Valves', 'type' => 'Inventory', 'description' => 'Industrial pumps and valves'],
            ['name' => 'Conveyor Components', 'type' => 'Inventory', 'description' => 'Conveyor belts, rollers, and accessories'],
            ['name' => 'Welding Supplies', 'type' => 'Inventory', 'description' => 'Welding equipment and consumables'],
            ['name' => 'Lubricants & Fluids', 'type' => 'Inventory', 'description' => 'Industrial lubricants and fluids'],
        ];

        $created = [];
        foreach ($groups as $group) {
            $created[$group['name']] = ItemGroup::create([
                'team_id' => $teamId,
                'type' => $group['type'],
                'item_group_name' => $group['name'],
                'description' => $group['description'],
                'returnable_item' => true,
                'images' => [],
                'unit' => 'Unit',
                'sales_account_id' => $salesAccountId,
                'purchases_account_id' => $purchaseAccountId,
                'inventory_account' => 'Inventory',
            ]);
        }

        $this->command->info('Item Groups created: ' . count($groups));
        return $created;
    }

    protected function getMiningSupplyItems(int $teamId, int $salesAccountId, int $purchaseAccountId): array
    {
        return [
            // ==================== DRILLING EQUIPMENT ====================
            [
                'team_id' => $teamId,
                'item_type' => 'Service',
                'name' => 'Sandvik DD422i Drill Rig',
                'sku' => 'SD-DD422I-001',
                'part_number' => 'DD422I',
                'unit' => 'Unit',
                'selling_price' => 2850000.00,
                'cost_price' => 2200000.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => false,
                'sales_description' => 'Sandvik DD422i development drill rig for underground mining',
                'purchases_description' => 'Sandvik DD422i development drill rig',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Service',
                'name' => 'Atlas Copco Boomer 282 Drill Rig',
                'sku' => 'AC-B282-001',
                'part_number' => 'B282',
                'unit' => 'Unit',
                'selling_price' => 3100000.00,
                'cost_price' => 2400000.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => false,
                'sales_description' => 'Atlas Copco Boomer 282 face drilling rig',
                'purchases_description' => 'Atlas Copco Boomer 282',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Sandvik T38 Drill Rod 3.66m',
                'sku' => 'SD-T38-366',
                'part_number' => 'T38-366',
                'unit' => 'Piece',
                'selling_price' => 1850.00,
                'cost_price' => 1200.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 500,
                'opening_stock_rate_per_unit' => 1200.00,
                'reorder_level' => 100,
                'sales_description' => 'Sandvik T38 extension drill rod 3.66 meters',
                'purchases_description' => 'Sandvik T38 drill rod',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Sandvik T45 Drill Rod 3.66m',
                'sku' => 'SD-T45-366',
                'part_number' => 'T45-366',
                'unit' => 'Piece',
                'selling_price' => 2100.00,
                'cost_price' => 1450.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 350,
                'opening_stock_rate_per_unit' => 1450.00,
                'reorder_level' => 75,
                'sales_description' => 'Sandvik T45 extension drill rod 3.66 meters',
                'purchases_description' => 'Sandvik T45 drill rod',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Sandvik Button Bit 76mm T38',
                'sku' => 'SD-BB76-T38',
                'part_number' => 'BB76-T38',
                'unit' => 'Piece',
                'selling_price' => 850.00,
                'cost_price' => 520.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 1000,
                'opening_stock_rate_per_unit' => 520.00,
                'reorder_level' => 200,
                'sales_description' => 'Sandvik 76mm carbide button bit T38 thread',
                'purchases_description' => 'Sandvik button bit 76mm',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Atlas Copco Button Bit 89mm T45',
                'sku' => 'AC-BB89-T45',
                'part_number' => 'BB89-T45',
                'unit' => 'Piece',
                'selling_price' => 980.00,
                'cost_price' => 620.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 800,
                'opening_stock_rate_per_unit' => 620.00,
                'reorder_level' => 150,
                'sales_description' => 'Atlas Copco 89mm carbide button bit T45 thread',
                'purchases_description' => 'Atlas Copco button bit 89mm',
            ],

            // ==================== SAFETY EQUIPMENT ====================
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'MSA Vigilant Self-Contained Self-Rescuer',
                'sku' => 'MSA-VIG-001',
                'part_number' => 'VIGILANT',
                'unit' => 'Unit',
                'selling_price' => 8500.00,
                'cost_price' => 5500.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 200,
                'opening_stock_rate_per_unit' => 5500.00,
                'reorder_level' => 50,
                'sales_description' => 'MSA Vigilant SCSR for underground mining emergency escape',
                'purchases_description' => 'MSA Vigilant SCSR',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Drager BG4 Closed Circuit Breathing Apparatus',
                'sku' => 'DG-BG4-001',
                'part_number' => 'BG4',
                'unit' => 'Unit',
                'selling_price' => 45000.00,
                'cost_price' => 32000.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 50,
                'opening_stock_rate_per_unit' => 32000.00,
                'reorder_level' => 15,
                'sales_description' => 'Drager BG4 CCBA for mine rescue operations',
                'purchases_description' => 'Drager BG4 breathing apparatus',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Hard Hat with Lamp Bracket',
                'sku' => 'PPE-HH-001',
                'part_number' => 'HHLAMP',
                'unit' => 'Piece',
                'selling_price' => 185.00,
                'cost_price' => 95.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 1000,
                'opening_stock_rate_per_unit' => 95.00,
                'reorder_level' => 200,
                'sales_description' => 'Mining hard hat with cap lamp bracket attachment',
                'purchases_description' => 'Hard hat with lamp bracket',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Koehler Cap Lamp LED',
                'sku' => 'KOE-LAMP-001',
                'part_number' => 'LIL-E',
                'unit' => 'Unit',
                'selling_price' => 2850.00,
                'cost_price' => 1850.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 300,
                'opening_stock_rate_per_unit' => 1850.00,
                'reorder_level' => 75,
                'sales_description' => 'Koehler LiL-E LED cap lamp for underground mining',
                'purchases_description' => 'Koehler LED cap lamp',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Mining Safety Boots Steel Toe',
                'sku' => 'PPE-BOOT-001',
                'part_number' => 'MSB-ST',
                'unit' => 'Pair',
                'selling_price' => 1250.00,
                'cost_price' => 780.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 500,
                'opening_stock_rate_per_unit' => 780.00,
                'reorder_level' => 100,
                'sales_description' => 'Mining safety boots with steel toe cap and metatarsal guard',
                'purchases_description' => 'Mining safety boots',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Nitrile Gloves Box 100',
                'sku' => 'PPE-NG-100',
                'part_number' => 'NG100',
                'unit' => 'Box',
                'selling_price' => 185.00,
                'cost_price' => 95.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 200,
                'opening_stock_rate_per_unit' => 95.00,
                'reorder_level' => 50,
                'sales_description' => 'Nitrile examination gloves - box of 100',
                'purchases_description' => 'Nitrile gloves box 100',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Safety Goggles Clear Lens',
                'sku' => 'PPE-SG-001',
                'part_number' => 'SG-CLR',
                'unit' => 'Pair',
                'selling_price' => 125.00,
                'cost_price' => 65.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 800,
                'opening_stock_rate_per_unit' => 65.00,
                'reorder_level' => 150,
                'sales_description' => 'Safety goggles with clear anti-fog lens',
                'purchases_description' => 'Safety goggles clear',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Dust Mask N95',
                'sku' => 'PPE-N95-001',
                'part_number' => 'N95',
                'unit' => 'Box',
                'selling_price' => 450.00,
                'cost_price' => 250.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 500,
                'opening_stock_rate_per_unit' => 250.00,
                'reorder_level' => 100,
                'sales_description' => 'N95 particulate respirator dust mask - box of 20',
                'purchases_description' => 'N95 dust mask box',
            ],

            // ==================== SPARE PARTS ====================
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'CAT 349E Hydraulic Pump',
                'sku' => 'CAT-349E-HP',
                'part_number' => '309-5510',
                'unit' => 'Unit',
                'selling_price' => 185000.00,
                'cost_price' => 125000.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 5,
                'opening_stock_rate_per_unit' => 125000.00,
                'reorder_level' => 2,
                'sales_description' => 'CAT 349E excavator main hydraulic pump',
                'purchases_description' => 'CAT 349E hydraulic pump',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'CAT C15 Engine Oil Filter',
                'sku' => 'CAT-C15-OF',
                'part_number' => '1R-0750',
                'unit' => 'Piece',
                'selling_price' => 1250.00,
                'cost_price' => 750.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 200,
                'opening_stock_rate_per_unit' => 750.00,
                'reorder_level' => 50,
                'sales_description' => 'CAT C15 engine oil filter genuine',
                'purchases_description' => 'CAT C15 oil filter',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'CAT Air Filter Element',
                'sku' => 'CAT-AF-001',
                'part_number' => '1R-1808',
                'unit' => 'Piece',
                'selling_price' => 2850.00,
                'cost_price' => 1650.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 100,
                'opening_stock_rate_per_unit' => 1650.00,
                'reorder_level' => 25,
                'sales_description' => 'CAT heavy duty air filter element',
                'purchases_description' => 'CAT air filter',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'SKF Spherical Roller Bearing 22320',
                'sku' => 'SKF-22320',
                'part_number' => '22320 EK/C3',
                'unit' => 'Piece',
                'selling_price' => 18500.00,
                'cost_price' => 11000.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 20,
                'opening_stock_rate_per_unit' => 11000.00,
                'reorder_level' => 5,
                'sales_description' => 'SKF spherical roller bearing 22320 EK/C3',
                'purchases_description' => 'SKF bearing 22320',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'SKF Deep Groove Ball Bearing 6310',
                'sku' => 'SKF-6310',
                'part_number' => '6310-2RS1',
                'unit' => 'Piece',
                'selling_price' => 1250.00,
                'cost_price' => 650.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 100,
                'opening_stock_rate_per_unit' => 650.00,
                'reorder_level' => 25,
                'sales_description' => 'SKF deep groove ball bearing 6310-2RS1 sealed',
                'purchases_description' => 'SKF bearing 6310',
            ],

            // ==================== CONVEYOR COMPONENTS ====================
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Conveyor Belt 1200mm x 10m Grade M',
                'sku' => 'CB-1200-10M',
                'part_number' => 'CB1200M',
                'unit' => 'Meter',
                'selling_price' => 2850.00,
                'cost_price' => 1850.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 500,
                'opening_stock_rate_per_unit' => 1850.00,
                'reorder_level' => 100,
                'sales_description' => 'Conveyor belt 1200mm width Grade M mining specification',
                'purchases_description' => 'Conveyor belt 1200mm Grade M',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Conveyor Idler 133mm x 1150mm',
                'sku' => 'CI-133-1150',
                'part_number' => 'ID1331150',
                'unit' => 'Piece',
                'selling_price' => 1650.00,
                'cost_price' => 950.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 200,
                'opening_stock_rate_per_unit' => 950.00,
                'reorder_level' => 50,
                'sales_description' => 'Conveyor idler roller 133mm diameter x 1150mm length',
                'purchases_description' => 'Conveyor idler 133mm',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Conveyor Pulley Lagging Rubber',
                'sku' => 'CP-LAG-001',
                'part_number' => 'LAG-12',
                'unit' => 'Sheet',
                'selling_price' => 4500.00,
                'cost_price' => 2800.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 50,
                'opening_stock_rate_per_unit' => 2800.00,
                'reorder_level' => 15,
                'sales_description' => 'Pulley lagging rubber sheet 12mm thick ceramic embedded',
                'purchases_description' => 'Pulley lagging rubber',
            ],

            // ==================== PUMPS ====================
            [
                'team_id' => $teamId,
                'item_type' => 'Service',
                'name' => 'Warman AH Slurry Pump 4x3',
                'sku' => 'WP-AH4X3',
                'part_number' => 'AH-4X3',
                'unit' => 'Unit',
                'selling_price' => 185000.00,
                'cost_price' => 125000.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => false,
                'sales_description' => 'Warman AH series slurry pump 4x3 inch',
                'purchases_description' => 'Warman AH slurry pump',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Warman Pump Impeller AH 4x3',
                'sku' => 'WP-IMP-4X3',
                'part_number' => 'A05-IMP',
                'unit' => 'Piece',
                'selling_price' => 28500.00,
                'cost_price' => 16500.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 15,
                'opening_stock_rate_per_unit' => 16500.00,
                'reorder_level' => 5,
                'sales_description' => 'Warman AH 4x3 pump impeller high chrome A05',
                'purchases_description' => 'Warman impeller',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Warman Pump Liner AH 4x3',
                'sku' => 'WP-LIN-4X3',
                'part_number' => 'A05-LIN',
                'unit' => 'Set',
                'selling_price' => 85000.00,
                'cost_price' => 55000.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 8,
                'opening_stock_rate_per_unit' => 55000.00,
                'reorder_level' => 3,
                'sales_description' => 'Warman AH 4x3 pump liner set high chrome A05',
                'purchases_description' => 'Warman pump liner set',
            ],

            // ==================== WELDING SUPPLIES ====================
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Lincoln Electric Welding Electrode E7018 3.2mm',
                'sku' => 'WE-E7018-32',
                'part_number' => 'E7018-3.2',
                'unit' => 'Kg',
                'selling_price' => 85.00,
                'cost_price' => 45.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 500,
                'opening_stock_rate_per_unit' => 45.00,
                'reorder_level' => 100,
                'sales_description' => 'Lincoln E7018 low hydrogen welding electrode 3.2mm',
                'purchases_description' => 'Welding electrode E7018 3.2mm',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Lincoln Electric Welding Electrode E6013 4.0mm',
                'sku' => 'WE-E6013-40',
                'part_number' => 'E6013-4.0',
                'unit' => 'Kg',
                'selling_price' => 65.00,
                'cost_price' => 35.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 800,
                'opening_stock_rate_per_unit' => 35.00,
                'reorder_level' => 150,
                'sales_description' => 'Lincoln E6013 general purpose welding electrode 4.0mm',
                'purchases_description' => 'Welding electrode E6013 4.0mm',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'MIG Welding Wire ER70S-6 1.2mm',
                'sku' => 'WE-MIG-12',
                'part_number' => 'ER70S-6-1.2',
                'unit' => 'Spool',
                'selling_price' => 850.00,
                'cost_price' => 450.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 100,
                'opening_stock_rate_per_unit' => 450.00,
                'reorder_level' => 25,
                'sales_description' => 'MIG welding wire ER70S-6 1.2mm 15kg spool',
                'purchases_description' => 'MIG wire 1.2mm',
            ],

            // ==================== LUBRICANTS ====================
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Shell Rimula R4 15W-40 Engine Oil 205L',
                'sku' => 'SH-RIM-R4',
                'part_number' => 'RIMULA-R4-205',
                'unit' => 'Drum',
                'selling_price' => 12500.00,
                'cost_price' => 8500.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 50,
                'opening_stock_rate_per_unit' => 8500.00,
                'reorder_level' => 15,
                'sales_description' => 'Shell Rimula R4 heavy duty diesel engine oil 205L drum',
                'purchases_description' => 'Shell Rimula R4 205L',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Shell Gadus S2 V220 Grease 180Kg',
                'sku' => 'SH-GAD-S2',
                'part_number' => 'GADUS-S2-180',
                'unit' => 'Drum',
                'selling_price' => 18500.00,
                'cost_price' => 12500.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 25,
                'opening_stock_rate_per_unit' => 12500.00,
                'reorder_level' => 8,
                'sales_description' => 'Shell Gadus S2 V220 multipurpose industrial grease 180kg',
                'purchases_description' => 'Shell Gadus grease 180kg',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Shell Tellus S2 MX 46 Hydraulic Oil 205L',
                'sku' => 'SH-TEL-S2',
                'part_number' => 'TELLUS-S2-205',
                'unit' => 'Drum',
                'selling_price' => 14500.00,
                'cost_price' => 9500.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 30,
                'opening_stock_rate_per_unit' => 9500.00,
                'reorder_level' => 10,
                'sales_description' => 'Shell Tellus S2 MX 46 hydraulic oil 205L drum',
                'purchases_description' => 'Shell Tellus hydraulic oil 205L',
            ],

            // ==================== ELECTRICAL ====================
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Armoured Cable 4 Core 95mm²',
                'sku' => 'AC-4C-95',
                'part_number' => 'AC4X95',
                'unit' => 'Meter',
                'selling_price' => 485.00,
                'cost_price' => 285.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 1000,
                'opening_stock_rate_per_unit' => 285.00,
                'reorder_level' => 200,
                'sales_description' => 'Steel wire armoured cable 4 core 95mm² copper',
                'purchases_description' => 'Armoured cable 4x95mm²',
            ],
            [
                'team_id' => $teamId,
                'item_type' => 'Inventory',
                'name' => 'Industrial Cable Gland M32 Brass',
                'sku' => 'CG-M32-BR',
                'part_number' => 'CGB32',
                'unit' => 'Piece',
                'selling_price' => 125.00,
                'cost_price' => 65.00,
                'sales_account_id' => $salesAccountId,
                'purchase_account_id' => $purchaseAccountId,
                'track_inventory_for_this_item' => true,
                'opening_stock' => 500,
                'opening_stock_rate_per_unit' => 65.00,
                'reorder_level' => 100,
                'sales_description' => 'Industrial brass cable gland M32',
                'purchases_description' => 'Cable gland M32 brass',
            ],
        ];
    }
}
